matrix:
  include:
    -
      language: objective-c
      osx_image: xcode8.3
      xcode_project: example/ios/example.xcworkspace
      xcode_scheme: example
      install:
        - nvm install 6.11.0
        - nvm use 6.11.0
        - cd example
        - npm install
        - cd ios
        - pod install
        - cd ..
        - node_modules/.bin/react-native link react-native-google-cast
      script:
        - node_modules/.bin/react-native bundle --entry-file index.ios.js --bundle-output `pwd`/output
        - cd ios
        - xcodebuild test -workspace example.xcworkspace -scheme example -destination 'platform=iOS Simulator,name=iPhone 6'
      #  - node_modules/.bin/jest --testPathPattern __tests__/index.ios.js
    - 
      language: android
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - extra
          - sys-img-armeabi-v7a-android-21
      before_script:
        - android list targets
        - echo no | android create avd --force -n test -t android-21 --abi armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell input keyevent 82 &
      install:
        - nvm install 6.11.0
        - nvm use 6.11.0
        - cd example
        - npm install
        - node_modules/.bin/react-native link react-native-google-cast
      script:
        - node_modules/.bin/react-native bundle --platform android --dev false --entry-file index.android.js --bundle-output android/app/src/main/assets/index.android.bundle --assets-dest android/app/src/main/res/
        - cd android
        - ./gradlew connectedAndroidTest
     #   - node_modules/.bin/jest --testPathPattern __tests__/index.android.js
