matrix:
  include:
    -
      language: objective-c
      osx_image: xcode8.3
      xcode_project: example/ios/example.xcworkspace
      xcode_scheme: example
      install:
        - nvm install 6.11.0
        - nvm use 6.11.0
        - cd example
        - npm install
        - cd ios
        - pod install
        - cd ..
        - node_modules/.bin/react-native link react-native-google-cast
      script:
        - node_modules/.bin/jest --testPathPattern __tests__/index.ios.js
    - 
      language: android
      android:
        components:
          - build-tools-23.0.1
          - android-23
          - extra
          - sys-img-armeabi-v7a-android-23
      install:
        - nvm install 6.11.0
        - nvm use 6.11.0   
        - cd example
        - npm install
      script:
        - node_modules/.bin/jest --testPathPattern __tests__/index.android.js
